
services:
  web:
    build: .
    container_name: time_capsule_app
    ports:
      - "8000:8000"
    command: gunicorn noteproject.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always